# Using Build-in functions

1. np.zeros(shape) -- an ndarray with a specified shape that is full of zeros.
2. np.ones(shape) -- an ndarray with a specified shape that is full of ones.
3. np.full(shape, constant value) -- an ndarray with a specified shape that is full of any number we want.
4. np.eye(shape) -- a square N x N ndarray corresponding to the identity matrix.
5. np.diag() -- Diagonal matrix --a square matrix that only has values in its main diagonal.

In [2]:
# Create a Numpy array of zeros with a desired shape
import numpy as np
X = np.zeros((3,4))
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [3]:
# Create a Numpy array of ones with a desired shape
X = np.ones((3,2))
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [4]:
# Create a Numpy array of constants with a desired shape
X = np.full((3,2), 5)
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[5 5]
 [5 5]
 [5 5]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In [5]:
# Create a Numpy array of an Identity matrix with a desired shape
X = np.eye(4)
print('X = \n', X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


Other methods in numpy:
1. numpy.arange()
    - Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)
    - It returns evenly spaced values within a given interval.


2. numpy.linspace()
    - Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    - It returns num evenly spaced values calculated over the interval [start, stop]


3. numpy.reshape
    - numpy.reshape(array, newshape, order='C')[source]
    - It returns an array containing the same data with a new shape.


4. numpy.random.random()
    - create an ndarray of the given shape with random floats in the half-open interval (0.0, 1.0)


5. np.random.randint(start, stop, size = shape)
    - reates an ndarray of the given shape with random integers in the half-open interval (start, stop).


6. numpy.random.normal()
    - Create a Numpy array of "Normal" distributed random numbers.
    

In [6]:
# Create a Numpy array of evenly spaced values in a given range, using arange(stop_val)
X = np.arange(10)
print('X = ', X)

# Create a Numpy array of evenly spaced values in a given range, using arange(start_val, stop_val)
X = np.arange(4,10)
print('X = ', X)

# Create a Numpy array of evenly spaced values in a given range, using arange(start_val, stop_val, step_size)
X = np.arange(1,14,3)
print('X = ', X)

X =  [0 1 2 3 4 5 6 7 8 9]
X =  [4 5 6 7 8 9]
X =  [ 1  4  7 10 13]


In [11]:
# Create a Numpy array of evenly spaced values in a given range, using linspace(start_val, stop_val, num_of_elements)
X = np.linspace(0,25,10)
print('X = ', X)

# Create a Numpy array of evenly spaced values in a given range, using linspace(start_val, stop_val, num_of_elements, endpoint=False)
X = np.linspace(0,25,10, endpoint=False)
print('X = ', X)

# Create a Numpy array of evenly spaced values in a given range, using linspace(start_val, stop_val, num_of_elements, endpoint=False, retstep=True)
# retstep=True returns the step size between the elements

X = np.linspace(0,25,10, endpoint=False, retstep=True)
print('X = ', X)
X = np.linspace(0,5,10, endpoint=True, retstep=True)
print('X = ', X)



X =  [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
X =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
X =  (array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5]), 2.5)
X =  (array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]), 0.5555555555555556)


In [16]:
# Create a Numpy array of evenly spaced values in a given range, using reshape(num_of_rows, num_of_cols)
X = np.arange(20).reshape(4,5)
print('X = \n', X)

X = np.arange(20).reshape(5,4)
print('X = \n', X)

X = np.arange(1,20,2).reshape(5,2)
print('X = \n', X)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
X = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
X = 
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
X = 
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# Create a Numpy array of evenly spaced values in a given range, using reshape(num_of_rows, num_of_cols) of order 'C'
# 'C' means row-major order
X = np.arange(20).reshape(4,5) # default order is 'C'
print('X = \n', X)

# Create a Numpy array of evenly spaced values in a given range, using reshape(num_of_rows, num_of_cols) of order 'F'
# 'F' means column-major order
X = np.arange(20).reshape(4,5, order='F')
print('X = \n', X)

# Create a Numpy array of evenly spaced values in a given range, using reshape(num_of_rows, num_of_cols) of order 'A'
# 'A' means 'F' if the array is Fortran contiguous in memory, 'C' otherwise
X = np.arange(20).reshape(4,5, order='A')
print('X = \n', X)

In [17]:
# Create a Numpy array using the numpy.random.random() function
X = np.random.random((3,3))
print('X = \n', X)

# Create a Numpy array using the numpy.random.randint() function
X = np.random.randint(4,15, (3,2))
print('X = \n', X)

# Create a Numpy array using the numpy.random.normal() function
X = np.random.normal(0,0.1, size=(1000,1000))
print('X = \n', X)
print('mean =', X.mean())
print('std =', X.std())
print('max =', X.max())
print('min =', X.min())
print('# positive =', (X > 0).sum())
print('# negative =', (X < 0).sum())

X = 
 [[0.55671232 0.29043201 0.93634613]
 [0.63318543 0.58582694 0.83111031]
 [0.23872559 0.96115731 0.59519467]]
X = 
 [[14  5]
 [ 7 14]
 [ 7 11]]
X = 
 [[-0.01655316  0.03641052 -0.16738444 ... -0.27118096 -0.09606345
  -0.13316218]
 [-0.00178157 -0.12432951 -0.13656818 ... -0.01674163 -0.31378124
  -0.04258121]
 [-0.03426621  0.00732329  0.15627388 ... -0.06538272  0.12285065
  -0.03054999]
 ...
 [ 0.14356047  0.05035809  0.02908675 ... -0.112424    0.09338922
  -0.00867005]
 [ 0.09979656 -0.08924061  0.02317091 ...  0.03426194  0.09808585
  -0.0024263 ]
 [-0.02538283  0.07364094 -0.10017821 ...  0.03245751  0.00099233
   0.0708541 ]]
mean = 8.06555973939159e-05
std = 0.10006170255804886
max = 0.46396044960397964
min = -0.5128115158144814
# positive = 500068
# negative = 499932


In [18]:
# Create a 4 X 4 ndarray that contains consecutive even numbers from 2 to 32 (inclusive)
X = np.arange(2,33,2).reshape(4,4)
print('X = \n', X)


In [22]:
import numpy as np

X = np.array([1,2,3,4,5])
print('X = ', X)

# Create a rank 1 ndarray
Y = np.array([6,7,8,9,10])

# Add X and Y
Z = X + Y
print('Z = ', Z)

# Access the element at index 3 of X
print('The element at index 3 of X is:', X[3])

# Delete the element at index 2 of Z
Z = np.delete(Z, 2)
print('Z = ', Z)

# Access the element at row 3, column 4 of X
X = np.arange(1,21).reshape(4,5)
print('X = \n', X)	
print('The element at row 3, column 4 of X is:', X[2,3])

# Delete the second row of X
# axis = 0 means row
X = np.delete(X, 1, axis=0)
print('X = \n', X)

# Delete the second and third columns of X
# axis = 1 means column
X = np.delete(X, [1,2], axis=1)
print('X = \n', X)

# Delete one element from X
# If you omit the axis parameter, the delete() function will treat the input array as a 1D vector and will append values along a new axis.
# In this case, it will delete the element at index 1
X = np.delete(X, 1)
print('X = \n', X)

# Delete multiple elements from X
# [1,2] means delete elements at index 1 and 2
X = np.delete(X, [1,2])
print('X = \n', X)

# Delete one element from each row of X
X = np.delete(X, [0,2], axis=1)
print('X = \n', X)

X =  [1 2 3 4 5]
Z =  [ 7  9 11 13 15]
The element at index 3 of X is: 4
Z =  [ 7  9 13 15]
X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
The element at row 3, column 4 of X is: 14
X = 
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]]
X = 
 [[ 1  4  5]
 [11 14 15]
 [16 19 20]]
X =  [ 1  4  5 11 14 15 16 19 20 10]
X =  [ 1  4  5 11 14 15 16 19 20 10 11 12 13]
X =  [ 1  4  5 11 14 15 16 19 20 10 11 12 13 11 12 13]


In [24]:
X = np.arange(1,21).reshape(4,5)

# Append the integer 10 to the end of X
X = np.append(X, 10)
print('X = ', X)

# Append the integer 11, 12 and 13 to the end of X as three separate elements
X = np.append(X, [11,12,13])
print('X = ', X)

# Append the integers 11, 12 and 13 to the end of X as a sequence
X = np.append(X, np.arange(11,14))
print('X = ', X)

X =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 10]
X =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 10 11 12 13]
X =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 10 11 12 13
 11 12 13]


In [33]:
X = np.arange(1,21).reshape(4,5)
print('X = \n', X)

# Insert the integer 10 into the beginning of X
# Without axis insert will flatten the array and insert the element at index 0
X = np.insert(X, 0, 10)
print('X = \n', X)

X = np.arange(1,21).reshape(4,5)

# Insert the integer 10 into the beginning of X as a separate row   
X = np.insert(X, 0, 10, axis=0)
print('X = \n', X)

# Insert the integers 10 and 11 as the third and fourth rows of X
X = np.insert(X, 2, [10,11,12,13,14], axis=0)
print('X = \n', X)

X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
X = 
 [10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
X = 
 [[10 10 10 10 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
X = 
 [[10 10 10 10 10]
 [ 1  2  3  4  5]
 [10 11 12 13 14]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
# Stack arrays vertically (row-wise)
X = np.arange(1,21).reshape(4,5)
Y = np.arange(21,41).reshape(4,5)
Z = np.vstack((X,Y))
print('Z = \n', Z)

# Stack arrays horizontally (column-wise)
Z = np.hstack((X,Y))
print('Z = \n', Z)


Z = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
Z = 
 [[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]
 [11 12 13 14 15 31 32 33 34 35]
 [16 17 18 19 20 36 37 38 39 40]]


In [ ]:
# Slicing 1D array
X = np.arange(1,21)
print('X = ', X)

# Get the elements from index 0 to index 9
print('X[0:10] = ', X[0:10])

# Get the elements from index 10 to the end of array
print('X[10:] = ', X[10:])
print('X[10:20] = ', X[10:20])

# Get the elements from index 0 to index 19 at an interval of 2
print('X[0:20:2] = ', X[0:20:2])

# Get every 4th element starting from index 1
print('X[1::4] = ', X[1::4])

# Get every 4th element starting from index 0
print('X[::4] = ', X[::4])

# Get every 4th element starting from index 0 from the end of the array
print('X[::-4] = ', X[::-4])


In [ ]:
# Slicing 2D array
X = np.arange(1,21).reshape(4,5)

# Get the first two rows and the last three columns
print('X[:2,2:] = \n', X[:2,2:])

# Get the first two rows and the last three columns in reverse order
print('X[1::-1,4::-1] = \n', X[1::-1,4::-1])

# Get the first two rows and the last three columns in reverse order
print('X[1::-1,4::-1] = \n', X[1::-1,4::-1])

In [37]:
# Here, slicing X and assigning it to Z doesn't create a copy of X
# Z is just another name for X and any changes made to X will be reflected in Z
# Slicing only creates a view of the original array. It does not create a new array.
X = np.arange(1,21).reshape(4,5)
print('X = \n', X)
Z = X[1:4,2:5]
print('Z = \n', Z)
X[1,2] = 20
print('X = \n', X)
print('Z = \n', Z)

X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Z = 
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
X = 
 [[ 1  2  3  4  5]
 [ 6  7 20  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Z = 
 [[20  9 10]
 [13 14 15]
 [18 19 20]]


In [38]:
# Using ndarray.copy(order='C'), creates a copy of the given ndarray
# order='C' means row-major order
X = np.arange(1,21).reshape(4,5)
print('X = \n', X)
Z = X[1:4,2:5].copy(order='C')
print('Z = \n', Z)
X[1,2] = 20
print('X = \n', X)
print('Z = \n', Z)

X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Z = 
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
X = 
 [[ 1  2  3  4  5]
 [ 6  7 20  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Z = 
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [40]:
# Use an array as indices to either make slices, select, or change elements of an array
X = np.arange(1,21).reshape(4,5)
print('X = \n', X)
Z = X[[0,1,2,3],[0,1,2,3]]
print('Z = ', Z)

indices = np.array([1,3])
print('indices = ', indices)
Y = X[indices,:]
print('Y = \n', Y)


X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Z =  [ 1  7 13 19]
indices =  [1 3]
Y = 
 [[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [43]:
# Use an array as indices to extract specific rows from a rank 2 ndarray.
X = np.random.randint(1,20, size=(50,5))
print('Shape of X = \n', X.shape)

# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(X)` (50)
row_indices = np.random.randint(0,50, size=10)
print('row_indices = ', row_indices)

# Print those rows of X whose indices are represented by entire row_indices ndarray
X_subset = X[row_indices, :]
print(X_subset)


Shape of X = 
 (50, 5)
row_indices =  [21 27 38 15 40  6 42 22 21  4]
[[ 9 11 17  2 14]
 [11 17 17  8 12]
 [ 7  8 10  1  6]
 [11 13  8 15 14]
 [ 6 18 18 17  5]
 [13 14  1 11  9]
 [16  4  3  5  4]
 [10  4 16 10 17]
 [ 9 11 17  2 14]
 [16 19  4 19  3]]


In [46]:
# Using numpy.diag() function
X = np.arange(1,26).reshape(5,5)
print('X = \n', X)
print('diag = ', np.diag(X))

# Using numpy.diag() function with k=1
# k=1 means diagonal above the main diagonal
print('diag = ', np.diag(X, k=1))

# Using numpy.diag() function with k=-1
# k=-1 means diagonal below the main diagonal
print('diag = ', np.diag(X, k=-2))


X = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
diag =  [ 1  7 13 19 25]
diag =  [ 2  8 14 20]
diag =  [11 17 23]


In [47]:
# Using numpy.unique() function
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('X = \n', X)
print('The unique elements in X are:', np.unique(X))

X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]
The unique elements in X are: [1 2 3 5 8]


In [49]:
# Boolean Indexing
X = np.arange(25).reshape(5,5)
print('X = \n', X)
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])
print('The elements in X that are between 10 and 17 or greater than 20:', X[((X > 10) & (X < 17)) | (X > 20)])

# Use the np.nonzero() function to print the indices of the elements in X that are greater than 10
print('The elements in X that are greater than 10:', np.nonzero(X > 10))

# Use the np.where() function to print the indices of the elements in X that are greater than 10
print('The elements in X that are greater than 10:', np.where(X > 10))

# Use the np.count_nonzero() function to print the number of elements in X that are greater than 10
print('Number of elements in X that are greater than 10:', np.count_nonzero(X > 10))

# Use the np.sum() function to print the number of elements in X that are greater than 10
print('Number of elements in X that are greater than 10:', np.sum(X > 10))

# Use the np.sum() function to print the number of elements in each column of X that are greater than 10
print('Number of elements in each column of X that are greater than 10:', np.sum(X > 10, axis=0))

# Use the np.sum() function to print the number of elements in each row of X that are greater than 10
print('Number of elements in each row of X that are greater than 10:', np.sum(X > 10, axis=1))

# Use the np.any() function to print out whether any elements in each column of X are greater than 10
print('Are there any elements greater than 10 in each column of X:', np.any(X > 10, axis=0))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]
The elements in X that are between 10 and 17 or greater than 20: [11 12 13 14 15 16 21 22 23 24]
The elements in X that are greater than 10: (array([2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))
The elements in X that are greater than 10: (array([2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))
Number of elements in X that are greater than 10: 14
Number of elements in X that are greater than 10: 14
Number of elements in each column of X that are greater than 10: [2 3 3 3 3]
Number of elements in each row of X that are greater than 10: [0 0 4 5 5]
Are there any elements greater than 10 in each co

In [52]:
# Set operations
X = np.array([1,2,3,4,5])
Y = np.array([6,7,2,8,4])
print('The elements that are both in X and Y:', np.intersect1d(X,Y))
print('The elements that are in X that are not in Y:', np.setdiff1d(X,Y))
print('All the elements of X and Y:', np.union1d(X,Y))

# Sorting
X = np.random.randint(1,11,size=(10,))
print('Original X = ', X)
print('Sorted X (out of place):', np.sort(X))
print('X after sorting:', X)
print('Sorted X (in-place):', np.sort(X, kind='quicksort'))
print('X after sorting:', X)
X.sort()
print('X after sorting:', X)
print('Sorted X (only unique elements):', np.sort(np.unique(X)))

# Sorting rows and columns
X = np.random.randint(1,11,size=(5,5))
print('Original X = \n', X)
print('Sorting the columns of X:\n', np.sort(X, axis=0))
print('Sorting the rows of X:\n', np.sort(X, axis=1))


The elements that are both in X and Y: [2 4]
The elements that are in X that are not in Y: [1 3 5]
All the elements of X and Y: [1 2 3 4 5 6 7 8]
Original X =  [ 5  5 10  6  5  2  3  5  7  2]
Sorted X (out of place): [ 2  2  3  5  5  5  5  6  7 10]
X after sorting: [ 5  5 10  6  5  2  3  5  7  2]
Sorted X (in-place): [ 2  2  3  5  5  5  5  6  7 10]
X after sorting: [ 5  5 10  6  5  2  3  5  7  2]
X after sorting: [ 2  2  3  5  5  5  5  6  7 10]
Sorted X (only unique elements): [ 2  3  5  6  7 10]
Original X = 
 [[ 7  1  1  3  9]
 [ 6 10  2  2  8]
 [ 6  6  4  1  1]
 [10  7 10  5  7]
 [ 4  9  9  3  2]]
Sorting the columns of X:
 [[ 4  1  1  1  1]
 [ 6  6  2  2  2]
 [ 6  7  4  3  7]
 [ 7  9  9  3  8]
 [10 10 10  5  9]]
Sorting the rows of X:
 [[ 1  1  3  7  9]
 [ 2  2  6  8 10]
 [ 1  1  4  6  6]
 [ 5  7  7 10 10]
 [ 2  3  4  9  9]]


In [54]:
# Broadcasting in Numpy
X = np.ones((3,3))
print('X = \n', X)
Y = np.arange(3)
print('Y = ', Y)
print('X + Y = \n', X + Y)
print('X + Y = \n', X *2 + Y)

# Broadcasting in Numpy in column-wise
X = np.ones((3,3))
print('X = \n', X)
Y = np.arange(3).reshape(3,1)
print('Y = \n', Y)
print('X + Y = \n', X + Y)


X = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Y =  [0 1 2]
X + Y = 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
X + Y = 
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


### [Link for mathematical functions in Numpy](https://numpy.org/devdocs/reference/routines.math.html#mathematical-functions)